name: "Quils in Space"
highlighter: rouge
markdown: kramdown
exclude:
  - node_modules
  - vendor
  
plugins:
  - jekyll-redirect-from

navigation:
  - text: Home
    url: /index.html
    group: home
  - text: Articles
    url: /topics
    group: blog
  - text: Art
    url: https://www.instagram.com/q.teatime/
    group: art
  - text: About
    url: /about
    group: about

collections:
  series:
    output: true
    permalink: /series/:path/
  topics:
    output: true
    permalink: /topics/:path/

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      group: blog
      permalink: /articles/:year/:title/
  - scope:
      path: _topics
      type: topics
    values:
      group: blog
      layout: category
  - scope:
      path: _series
      type: series
    values:
      group: blog
      layout: serie